module constants_m
  implicit none
  real(8),parameter :: delx=3d0,dely=3d0 !km, for BG earth grid---
  integer(kind=2),parameter:: maxfovsiz=800

  real(8),parameter :: zero=1d-6
  real(8),parameter :: zero_d=1d-9
  real(8),parameter:: pi=3.141592653589793d0
  real(8),parameter:: deg2rad=pi/180d0
  real(8),parameter:: rad2deg=180d0/pi

  !// The following constant definitions are the WGS84 Earth Ellipsoid
  !// constants.  The main reference for the WGS84 ellipsoid is
  !// NIMA Physical Geodesy web page: 164.214.2.59/GandG/wgs-84/egm96.htm
  real(kind=8),parameter :: EQUAT_RAD = 6.37813700000000d+6 ! // Equatoral rad.,meters WGS84
  real(kind=8),parameter :: POLAR_RAD = 6.35675231424518d+6 ! // Polar radius,meters WGS84
  real(kind=8),parameter :: ECCEN_SQ  = 6.69437999014132d-3 ! // EccentricitySquared WGS84
  real(kind=8),parameter :: FLATFAC   = 1d0/298.257223563d0 ! // FlatteningFactor WGS84
  real(kind=8),parameter :: max_lat_diff  = 1d-10
  real(8),parameter :: rmissing=-999d0
  integer(4),parameter :: imissing=-999

  !For building orbit in ECI ---------------------------------------------------------------
  !real(kind=8),parameter  :: leapsecs  = 37 !for 2017
  real(kind=8),parameter   :: leapsecs  = 36 !for 2016
  !real(kind=8),parameter  :: leapsecs  = 35 !for 2014
  real(kind=8),parameter   :: secsdif19581900 = 1830297600.D0
  real(kind=8),parameter   :: SEC_IN_DAY    = 86400.0d0
  INTEGER(KIND=8),PARAMETER:: SEC_IN_HOUR   = 3600
  INTEGER(KIND=8),PARAMETER:: SEC_IN_MINUTE = 60
  REAL(KIND=8),PARAMETER ::  JD1900 = 2415021d0
  real(kind=8),parameter ::  UJD58        = 2.43620450d+06 !Jan 1 1958 UJDformat
  real(kind=8),parameter ::  UJD00        = 2.45154500d+06 !julian date of 2000/01/01/12/00/00
  real(kind=8),parameter ::  TTmTAI    = 32.184d0    !-- seconds
  real(kind=8),parameter::OMEGA = 7.292115870409d-5
  !For buid orbit frame in ECI, copy ARTS------------------------
  real(kind=8),parameter ::  DETIC2CENTRIC = 9.93305620009859d-1
  real(kind=8),parameter ::  KILO      = 1000.0d0
  real(kind=8),parameter ::  delta         = 6.73950125d-3
  real(kind=8),parameter ::  eq_radius     = 6.3781370d+3


!for L-BFGS-B----------------------------------------
  integer(kind=4),parameter :: mcorrection=20,iprint=1,iterlimit=1000
  real(8) ,parameter :: factr=0.d0,pgtol=0.d0,tlimit=600d0
!mcorrection is an INTEGER variable that must be set by the user to the
!            number of corrections used in the limited memory matrix.
!            It is not altered by the routine.  Values of m < 3  are
!            not recommended, and large values of m can result in excessive
!            computing time. The range  3 <= m <= 20 is recommended.
!iprint      is an INTEGER variable that must be set by the user.
!            It controls the frequency and type of output generated:
!            iprint<0    no output is generated;
!            iprint=0    print only one line at the last iteration;
!            0<iprint<99 print also f and |proj g| every iprint iterations;
!            iprint=99   print details of every iteration except n-vectors;
!            iprint=100  print also the changes of active set and final x;
!            iprint>100  print details of every iteration including x and g;
!            When iprint > 0, the file iterate.dat will be created to
!            summarize the iteration.
!iterlimit   limit of iteration number
!factr       is a DOUBLE PRECISION variable that must be set by the user.
!            It is a tolerance in the termination test for the algorithm.
!            The iteration will stop when
!            (f^k - f^{k+1})/max{|f^k|,|f^{k+1}|,1} <= factr*epsmch
!            where epsmch is the machine precision which is automatically
!            generated by the code. Typical values for factr on a computer
!            with 15 digits of accuracy in double precision are:
!            factr=1.d+12 for low accuracy;
!                  1.d+7  for moderate accuracy;
!                  1.d+1  for extremely high accuracy.
!            The user can suppress this termination test by setting factr=0.
!pgtol       is a double precision variable.
!            On entry pgtol >= 0 is specified by the user.  The iteration
!            will stop when
!            max{|proj g_i | i = 1, ..., n} <= pgtol
!            where pg_i is the ith component of the projected gradient.
!            The user can suppress this termination test by setting pgtol=0.
!tlimit      limit of running time (seconds)





end module constants_m
